// <auto-generated />
using System;
using Iam.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iam.Repository.Migrations
{
    [DbContext(typeof(AppIamContext))]
    [Migration("20251129162244_SeedingNewTipoDocumento")]
    partial class SeedingNewTipoDocumento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Iam.Domain.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Descripcion = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Descripcion = "Usuario"
                        });
                });

            modelBuilder.Entity("Iam.Domain.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Sectores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("291aefbb-1f66-4aff-a30c-6163d726c43c"),
                            Nombre = "Desarrollo"
                        },
                        new
                        {
                            Id = new Guid("c6eb1013-ea61-4f0d-9774-ace21596a02a"),
                            Nombre = "Diseño"
                        },
                        new
                        {
                            Id = new Guid("faafefc4-9368-4624-93ac-1b7a734e7000"),
                            Nombre = "Calidad"
                        },
                        new
                        {
                            Id = new Guid("e69d41f0-5a46-4b9d-840a-dd76d55c92cd"),
                            Nombre = "Investigacion"
                        },
                        new
                        {
                            Id = new Guid("e6f5f7ca-079e-4a5c-b1cb-d03f953a21b2"),
                            Nombre = "Administracion"
                        });
                });

            modelBuilder.Entity("Iam.Domain.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Nombre = "DNI"
                        },
                        new
                        {
                            Id = new Guid("e9210cfd-f497-428a-81d9-dd7cae9a0adf"),
                            Nombre = "Pasaporte"
                        },
                        new
                        {
                            Id = new Guid("34ed1c14-f92a-4b29-b5e4-4a0fef9e9ec3"),
                            Nombre = "Cedula de Ciudadania"
                        });
                });

            modelBuilder.Entity("Iam.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("TipoDocumentoId", "NroDocumento")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Iam.Domain.UsuarioXSector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("SectorId");

                    b.HasIndex("UsuarioId", "SectorId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuariosXSectores", (string)null);
                });

            modelBuilder.Entity("Iam.Domain.Usuario", b =>
                {
                    b.HasOne("Iam.Domain.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iam.Domain.TipoDocumento", "TipoDocumento")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Iam.Domain.UsuarioXSector", b =>
                {
                    b.HasOne("Iam.Domain.Rol", "Rol")
                        .WithMany("UsuarioXSector")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iam.Domain.Sector", "Sector")
                        .WithMany("UsuarioXSector")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iam.Domain.Usuario", "Usuario")
                        .WithMany("Sectores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sector");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Iam.Domain.Rol", b =>
                {
                    b.Navigation("UsuarioXSector");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Iam.Domain.Sector", b =>
                {
                    b.Navigation("UsuarioXSector");
                });

            modelBuilder.Entity("Iam.Domain.TipoDocumento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Iam.Domain.Usuario", b =>
                {
                    b.Navigation("Sectores");
                });
#pragma warning restore 612, 618
        }
    }
}
