// <auto-generated />
using System;
using Expedientes.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expedientes.Repository.Migrations
{
    [DbContext(typeof(AppExpedientesContext))]
    [Migration("20251104170837_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Expedientes.Domain.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ee0e381-e5f1-43e4-9f26-059280df1b32"),
                            Descripcion = "Creado"
                        },
                        new
                        {
                            Id = new Guid("d4d07350-31e4-4b84-b726-713a13702a6d"),
                            Descripcion = "EnTramite"
                        },
                        new
                        {
                            Id = new Guid("138c7d7f-91a1-49ef-a1b8-383ea0e21248"),
                            Descripcion = "Cerrado"
                        });
                });

            modelBuilder.Entity("Expedientes.Domain.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caratula")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("EstadoActualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubTema")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoActualId");

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("Expedientes.Domain.Foja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("Fojas", (string)null);
                });

            modelBuilder.Entity("Expedientes.Domain.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<Guid>("SectorDesdeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorHastaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ExpedienteId", "Fecha");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("Expedientes.Domain.Expediente", b =>
                {
                    b.HasOne("Expedientes.Domain.Estado", "EstadoActual")
                        .WithMany("Expedientes")
                        .HasForeignKey("EstadoActualId")
                        .IsRequired();

                    b.Navigation("EstadoActual");
                });

            modelBuilder.Entity("Expedientes.Domain.Foja", b =>
                {
                    b.HasOne("Expedientes.Domain.Expediente", "Expediente")
                        .WithMany("Fojas")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Expedientes.Domain.Movimiento", b =>
                {
                    b.HasOne("Expedientes.Domain.Estado", "Estado")
                        .WithMany("Movimientos")
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("Expedientes.Domain.Expediente", "Expediente")
                        .WithMany("Movimientos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Expedientes.Domain.Estado", b =>
                {
                    b.Navigation("Expedientes");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Expedientes.Domain.Expediente", b =>
                {
                    b.Navigation("Fojas");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
