// <auto-generated />
using System;
using Expedientes.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expedientes.Repository.Migrations
{
    [DbContext(typeof(AppExpedientesContext))]
    [Migration("20251130131712_AddingUsuarioToMovimiento")]
    partial class AddingUsuarioToMovimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Expedientes.Domain.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc43dac0-a951-4107-86e5-d63cdaf764e2"),
                            Descripcion = "Creado"
                        },
                        new
                        {
                            Id = new Guid("e5b8de27-5d78-457a-913d-89a4e634b0c6"),
                            Descripcion = "En revisión"
                        },
                        new
                        {
                            Id = new Guid("be14b378-9742-4c20-bdfe-0bf9d8eacc0e"),
                            Descripcion = "En progreso"
                        },
                        new
                        {
                            Id = new Guid("1907e192-d38e-4564-a949-cfad5af7ee0a"),
                            Descripcion = "Aprobado"
                        },
                        new
                        {
                            Id = new Guid("1fbf4dc3-cb0c-405e-b0a4-9ea72076b637"),
                            Descripcion = "Rechazado"
                        },
                        new
                        {
                            Id = new Guid("80d71e53-5ab3-418b-91ed-980b2e40595e"),
                            Descripcion = "Completado"
                        });
                });

            modelBuilder.Entity("Expedientes.Domain.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caratula")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("EstadoActualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdSectorActual")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubTema")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoActualId");

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("Expedientes.Domain.Foja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("Fojas", (string)null);
                });

            modelBuilder.Entity("Expedientes.Domain.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<Guid>("SectorDesdeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorHastaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ExpedienteId", "Fecha");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("Expedientes.Domain.Expediente", b =>
                {
                    b.HasOne("Expedientes.Domain.Estado", "EstadoActual")
                        .WithMany("Expedientes")
                        .HasForeignKey("EstadoActualId")
                        .IsRequired();

                    b.Navigation("EstadoActual");
                });

            modelBuilder.Entity("Expedientes.Domain.Foja", b =>
                {
                    b.HasOne("Expedientes.Domain.Expediente", "Expediente")
                        .WithMany("Fojas")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Expedientes.Domain.Movimiento", b =>
                {
                    b.HasOne("Expedientes.Domain.Estado", "Estado")
                        .WithMany("Movimientos")
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("Expedientes.Domain.Expediente", "Expediente")
                        .WithMany("Movimientos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Expedientes.Domain.Estado", b =>
                {
                    b.Navigation("Expedientes");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Expedientes.Domain.Expediente", b =>
                {
                    b.Navigation("Fojas");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
